#!/bin/sh

set -e

echo "Running pre-push hook:"

echo "Executing: cargo fmt"
cargo fmt

echo "Executing: cargo clippy --all-targets --workspace -- -D warnings"
find . | grep "\.\/src\/.*\.rs$" | xargs touch ; cargo clippy --all-targets --workspace -- -D warnings
