apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      operator-sdk/primary-resource: monitoring/kiali
      operator-sdk/primary-resource-type: Kiali.kiali.io
    creationTimestamp: "2022-06-27T16:33:07Z"
    labels:
      app: kiali
      app.kubernetes.io/instance: kiali
      app.kubernetes.io/name: kiali
      app.kubernetes.io/part-of: kiali
      app.kubernetes.io/version: v1.41.0
      version: v1.41.0
    name: kiali
    namespace: default
    resourceVersion: "102143364"
    uid: f0de3ac8-1680-4794-88c3-927a42cccce0
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kiali-viewer
  subjects:
  - kind: ServiceAccount
    name: kiali-service-account
    namespace: monitoring
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
